/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedGalleryRouteImport } from './routes/_authenticated/gallery'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedReferencesIndexRouteImport } from './routes/_authenticated/references/index'
import { Route as AuthenticatedReferencesCollectionIdRouteImport } from './routes/_authenticated/references/$collectionId'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsGenerationRouteImport } from './routes/_authenticated/settings/generation'
import { Route as AuthenticatedSettingsReferencesRouteImport } from './routes/_authenticated/settings/references'
import { Route as AuthenticatedSettingsUsageRouteImport } from './routes/_authenticated/settings/usage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGalleryRoute = AuthenticatedGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferencesIndexRoute =
  AuthenticatedReferencesIndexRouteImport.update({
    id: '/references/',
    path: '/references/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReferencesCollectionIdRoute =
  AuthenticatedReferencesCollectionIdRouteImport.update({
    id: '/references/$collectionId',
    path: '/references/$collectionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsGenerationRoute =
  AuthenticatedSettingsGenerationRouteImport.update({
    id: '/generation',
    path: '/generation',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsReferencesRoute =
  AuthenticatedSettingsReferencesRouteImport.update({
    id: '/references',
    path: '/references',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsUsageRoute =
  AuthenticatedSettingsUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/references/$collectionId': typeof AuthenticatedReferencesCollectionIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/generation': typeof AuthenticatedSettingsGenerationRoute
  '/settings/references': typeof AuthenticatedSettingsReferencesRoute
  '/settings/usage': typeof AuthenticatedSettingsUsageRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/references/': typeof AuthenticatedReferencesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/gallery': typeof AuthenticatedGalleryRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/references/$collectionId': typeof AuthenticatedReferencesCollectionIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/generation': typeof AuthenticatedSettingsGenerationRoute
  '/settings/references': typeof AuthenticatedSettingsReferencesRoute
  '/settings/usage': typeof AuthenticatedSettingsUsageRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/references': typeof AuthenticatedReferencesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/gallery': typeof AuthenticatedGalleryRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/references/$collectionId': typeof AuthenticatedReferencesCollectionIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/generation': typeof AuthenticatedSettingsGenerationRoute
  '/_authenticated/settings/references': typeof AuthenticatedSettingsReferencesRoute
  '/_authenticated/settings/usage': typeof AuthenticatedSettingsUsageRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/references/': typeof AuthenticatedReferencesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/dashboard'
    | '/gallery'
    | '/projects/$projectId'
    | '/references/$collectionId'
    | '/settings/account'
    | '/settings/generation'
    | '/settings/references'
    | '/settings/usage'
    | '/projects/'
    | '/references/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/gallery'
    | '/projects/$projectId'
    | '/references/$collectionId'
    | '/settings/account'
    | '/settings/generation'
    | '/settings/references'
    | '/settings/usage'
    | '/projects'
    | '/references'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/gallery'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/references/$collectionId'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/generation'
    | '/_authenticated/settings/references'
    | '/_authenticated/settings/usage'
    | '/_authenticated/projects/'
    | '/_authenticated/references/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gallery': {
      id: '/_authenticated/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthenticatedGalleryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/references/': {
      id: '/_authenticated/references/'
      path: '/references'
      fullPath: '/references/'
      preLoaderRoute: typeof AuthenticatedReferencesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/references/$collectionId': {
      id: '/_authenticated/references/$collectionId'
      path: '/references/$collectionId'
      fullPath: '/references/$collectionId'
      preLoaderRoute: typeof AuthenticatedReferencesCollectionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/generation': {
      id: '/_authenticated/settings/generation'
      path: '/generation'
      fullPath: '/settings/generation'
      preLoaderRoute: typeof AuthenticatedSettingsGenerationRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/references': {
      id: '/_authenticated/settings/references'
      path: '/references'
      fullPath: '/settings/references'
      preLoaderRoute: typeof AuthenticatedSettingsReferencesRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/usage': {
      id: '/_authenticated/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof AuthenticatedSettingsUsageRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsGenerationRoute: typeof AuthenticatedSettingsGenerationRoute
  AuthenticatedSettingsReferencesRoute: typeof AuthenticatedSettingsReferencesRoute
  AuthenticatedSettingsUsageRoute: typeof AuthenticatedSettingsUsageRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsGenerationRoute: AuthenticatedSettingsGenerationRoute,
    AuthenticatedSettingsReferencesRoute: AuthenticatedSettingsReferencesRoute,
    AuthenticatedSettingsUsageRoute: AuthenticatedSettingsUsageRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGalleryRoute: typeof AuthenticatedGalleryRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedReferencesCollectionIdRoute: typeof AuthenticatedReferencesCollectionIdRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedReferencesIndexRoute: typeof AuthenticatedReferencesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGalleryRoute: AuthenticatedGalleryRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedReferencesCollectionIdRoute:
    AuthenticatedReferencesCollectionIdRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedReferencesIndexRoute: AuthenticatedReferencesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
